export type DocStatus = "submitted" | "review" | "payment" | "released"

export interface ApplicationStage {
  label: string
  done: boolean
  note?: string
  date?: string
}

export interface Application {
  id: string
  service: string
  who: string
  status: DocStatus
  track: string
  submitted: string
  stages: ApplicationStage[]
  attachments?: string[]
}

/** Reusable, long-term identity documents only. Lives in the Document Wallet. */
export interface WalletDoc {
  id: string
  name: string
  category: string
  status: "verified" | "pending" | "missing"
  updated?: string
  fileNote?: string
}

/** A document generated by the LGU after an application is approved. */
export interface IssuedDocument {
  id: string
  applicationId: string
  title: string
  type: "Official Receipt" | "Certificate" | "Permit" | "Clearance"
  service: string
  track: string
  issuedDate: string
}

export interface RequestFieldConfig {
  id: string
  label: string
  type: "text" | "select" | "date" | "number"
  placeholder?: string
  options?: string[]
  required?: boolean
}

/** A document required specifically for one application. Uploaded fresh every time, never saved to the wallet. */
export interface AttachmentRequirement {
  id: string
  label: string
  helpText?: string
  required: boolean
}

export interface RequestTypeConfig {
  slug: string
  title: string
  shortLabel: string
  description: string
  icon: string
  trackPrefix: string
  /** "standard" = Details -> Attachments -> Review engine. "cart" = routes to its own dedicated flow (e.g. RPT). */
  flowType: "standard" | "cart"
  fields: RequestFieldConfig[]
  /** Reusable identity documents pulled from the Document Wallet, e.g. "Valid government ID". Empty if the service doesn't need identity (e.g. RPT). */
  identityRequirements: string[]
  /** One-off documents specific to this application, uploaded fresh and not stored in the wallet. */
  attachmentRequirements: AttachmentRequirement[]
}

export interface Hotline {
  id: string
  name: string
  number: string
  category: "Police" | "Fire" | "Medical" | "Disaster" | "Barangay"
  note?: string
}

export interface ReportCategory {
  id: string
  label: string
  icon: string
}

export interface ChatMessage {
  id: string
  role: "user" | "assistant"
  text: string
}

